docs/planejamento/ferramentas.md

Este Pull Request adiciona a seção "Ferramentas" ao documento, descrevendo os recursos que serão utilizados pela equipe ao longo do desenvolvimento do projeto. As ferramentas foram organizadas nas seguintes categorias:
Comunicação
Versionamento e Manutenção do Projeto
Organização
Documentação
Armazenamento e Publicação

 (#P01): Adiciona conteudo ao tópico Ferramentas

---

docs/index.md

adição da home page

---

docs/index.md
docs/planejamento/equipe.md
mkdocs.yml

:bug: FIX: consertando imagens

---

docs/gravacoes/entregas/entregas.md
docs/gravacoes/reunioes/reunioes.md

(#P01)  configuracao/repositorio de gravacoes

---

docs/planejamento/termo-de-uso.md

adicionando a lista de termos de uso do aplicativo

(#P01) termos de uso

---

docs/planejamento/termo-de-uso.md

:memo: (#P01) atualizacao da descricao

---

docs/gravacoes/reunioes/ata-dia-10-04-2025.md
docs/gravacoes/reunioes/ata-dia-15-04-2025.md

Criação dos documentos de atas de reunião para os dias 10 (quinta-feira) e 15 (terça-feira) de abril.

#D03 adição das atas de reunião dos dias 10/4 e 15/04

---

docs/tecnicas-de-elicitacao/entrevista/roteiro-de-entrevista.md
docs/tecnicas-de-elicitacao/entrevista/termo-de-consentimento.md

Adição dos documentos: roteiro de entrevista e termo de consentimento para a entrevista

#E01 adição roteiro de entrevista

---

docs/priorizacao/three-level-scale.md

depois vi um erro de formatação no histórico de versões e coloquei um link como link de fato

(#P01) - conserta formatacao na tabela e no link

---

docs/planejamento/lista-de-apps-avaliados.md

foi adicionado o deepseek na lista de apps analisados e expliquei que o guardioes da saude foi utilizado anteriormente mas depois mudamos

#P02 - adiciona deepseek na lista de apps analisados

---

docs/planejamento/termo-de-uso.md

Adiciona termos novos

---

docs/doc-guardioes-da-saude/tecnicas-de-elicitacao/questionario/ElicitacaoQuestionario.md

 Correção da tabela de requisitos do questionário/ projeto obsoleto

---

docs/modelagem/lexicos.md

Adição dos léxicos dos casos de uso não implementados: cancelamento de mensagem em andamento e visualização do status do servidor em tempo real

#LX01 adição de novos léxicos

---

docs/modelagem/casos-de-uso.md

Adição dos casos de uso: cancelamento de mensagem que está sendo gerada pela IA e visualização do status do servidor no momento

#UC02 adição de novos casos de uso

---

docs/gravacoes/reunioes/ata-dia-15-05-2025.md
mkdocs.yml

Adição do documento da ata e da página da ata no mkdocs

#D04 adição da ata do dia 15-05

---

docs/modelagem/cenarios.md
docs/modelagem/lexicos.md

Adição dos cenários das funcionalidades não implementadas: visualização de status do servidor e cancelamento de mensagem em andamento

#C02 adição de novos cenários

---

docs/modelagem/cenarios.md

adicionei novos cenarios no fim da página, seguindo a numeracao.
tem que adicionar revisor

adicao novos cenarios

---

docs/modelagem/casos-de-uso.md

#CU-AnaJoyce exclusao automatica de dados

---

docs/modelagem/nfr-framework.md

so fiz umas correcoes na minha parte

correcoes nas dependencias

---

docs/rastreabilidade/pos-rastreabilidade.md

#PR01 add RN do 04 ao 09 exceto 06

---

docs/modelagem/backlog.md
docs/modelagem/historias-de-usuario.md
docs/modelagem/nfr-framework.md

Adição de hiperlinks nos documentos da entrega

Melhorias entrega 4

---

docs/gravacoes/entregas/grav-entrega.md
docs/inspecao/entrega6/inpecao-grupo3.md
mkdocs.yml

Inspeção grupo 3

---

docs/planejamento/ferramentas.md

[Incremento 1]:
:memo: | :bug: (#D010): Adição da Ferramenta "Figma", ajuste no histórico de versionamento, correção do bug com hiperlinks das referências (Remoção dos "#" em ids dos elementos de ancoragem: "<a></a>").

:memo: Melhorias para Entrega 1
